ExternalProject_Add(aliceVision
       PREFIX ${CMAKE_CURRENT_SOURCE_DIR}
       BUILD_IN_SOURCE 0
       BUILD_ALWAYS 1
       SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src
       BINARY_DIR ${BUILD_DIR}/aliceVision_build
       INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
       CMAKE_ARGS
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
	    -DBUILD_SHARED_LIBS=ON
	    -DTARGET_ARCHITECTURE=core
            -DALICEVISION_ROOT=${ALICEVISION_ROOT}
            -DALICEVISION_USE_ALEMBIC=ON
            -DMINIGLOG=ON
            -DALICEVISION_USE_CCTAG=${AV_BUILD_CCTAG}
            -DALICEVISION_USE_APRILTAG=${AV_BUILD_APRILTAG}
            -DALICEVISION_USE_OPENCV=${AV_BUILD_OPENCV}
            -DALICEVISION_USE_OPENGV=${AV_BUILD_OPENGV}
            -DALICEVISION_USE_POPSIFT=${AV_BUILD_POPSIFT}
            -DALICEVISION_USE_CUDA=${AV_USE_CUDA}
            -DALICEVISION_BUILD_DOC=OFF
            -DALICEVISION_BUILD_EXAMPLES=OFF
            ${ZLIB_CMAKE_FLAGS}
            ${ASSIMP_CMAKE_FLAGS}
            ${EIGEN_CMAKE_FLAGS}
            ${OPENIMAGEIO_CMAKE_FLAGS}
            ${OPENEXR_CMAKE_FLAGS}
            ${BOOST_CMAKE_FLAGS}
            ${ALEMBIC_CMAKE_FLAGS}
            ${GEOGRAM_CMAKE_FLAGS}
            ${LAPACK_CMAKE_FLAGS}
            ${CERES_CMAKE_FLAGS}
            ${CUDA_CMAKE_FLAGS}
            ${POPSIFT_CMAKE_FLAGS}
            ${OPENGV_CMAKE_FLAGS}
            ${OPENCV_CMAKE_FLAGS}
            ${CCTAG_CMAKE_FLAGS}
            ${APRILTAG_CMAKE_FLAGS}
            ${EXPAT_CMAKE_FLAGS}
            ${COINUTILS_CMAKE_FLAGS}
	    ${OSI_CMAKE_FLAGS}
	    ${CLP_CMAKE_FLAGS}
            ${LZ4_CMAKE_FLAGS}
            ${FLANN_CMAKE_FLAGS}
            ${PCL_CMAKE_FLAGS}
            ${USD_CMAKE_FLAGS}
            -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR> <SOURCE_DIR>
       DEPENDS ${AV_DEPS}
)
