ExternalProject_Add(${CCTAG_TARGET}
      GIT_REPOSITORY ${CCTAG_URI}
      GIT_TAG ${CCTAG_VERSION}
      PREFIX ${BUILD_DIR}
      BUILD_ALWAYS 0
      SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/cctag
      BINARY_DIR ${BUILD_DIR}/cctag_build
      INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
      CMAKE_ARGS
          ${CMAKE_CORE_BUILD_FLAGS}
          ${BOOST_CMAKE_FLAGS}
          ${CUDA_CMAKE_FLAGS}
          ${OPENCV_CMAKE_FLAGS}
          ${EIGEN_CMAKE_FLAGS}
          ${TBB_CMAKE_FLAGS}
          -DCCTAG_WITH_CUDA=${AV_USE_CUDA}
          -DCCTAG_BUILD_TESTS=OFF
          -DCCTAG_BUILD_APPS=OFF
          -DCCTAG_EIGEN_MEMORY_ALIGNMENT=ON
          -DCCTAG_CXX_STANDARD=17
          -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
          <SOURCE_DIR>
      BUILD_COMMAND $(MAKE) -j${AV_BUILD_DEPENDENCIES_PARALLEL}
      DEPENDS ${BOOST_TARGET} ${CUDA_TARGET} ${OPENCV_TARGET} ${EIGEN_TARGET} ${TBB_TARGET}
)

set(CCTAG_CMAKE_FLAGS -DCCTag_DIR:PATH=${CMAKE_INSTALL_PREFIX}/lib/cmake/CCTag)
