ExternalProject_Add(${CLP_TARGET}
      GIT_REPOSITORY ${CLP_URI}
      GIT_TAG ${CLP_VERSION}
      PREFIX ${BUILD_DIR}
      BUILD_ALWAYS 0
      SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/clp
      BINARY_DIR ${BUILD_DIR}/clp_build
      INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
      CMAKE_ARGS
          ${CMAKE_CORE_BUILD_FLAGS}
          -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
          <SOURCE_DIR>
      BUILD_COMMAND $(MAKE) -j${AV_BUILD_DEPENDENCIES_PARALLEL}
      DEPENDS ${COINUTILS_TARGET} ${OSI_TARGET}
)

set(CLP_CMAKE_FLAGS -DClp_DIR:PATH=${CMAKE_INSTALL_PREFIX}/share/clp)
