set(EXPAT_TARGET expat)
ExternalProject_Add(${EXPAT_TARGET}
       GIT_REPOSITORY ${EXPAT_URI}
       GIT_TAG ${EXPAT_VERSION}
       PREFIX ${BUILD_DIR}
       BUILD_ALWAYS 0
       SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/expat
       BINARY_DIR ${BUILD_DIR}/libexpat_build
       INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
       CONFIGURE_COMMAND ${CMAKE_COMMAND} ${CMAKE_CORE_BUILD_FLAGS}
           -DEXPAT_BUILD_DOCS=OFF
           -DEXPAT_BUILD_EXAMPLES=OFF
           -DEXPAT_BUILD_TOOLS=OFF
           -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
           <SOURCE_DIR>/expat
       BUILD_COMMAND $(MAKE) -j${AV_BUILD_DEPENDENCIES_PARALLEL}
)
