set(ENV{PKG_CONFIG_PATH "${CMAKE_INSTALL_PREFIX}/lib/pkgconfig")

ExternalProject_Add(${FLANN_TARGET}
	GIT_REPOSITORY ${FLANN_URI}
	GIT_TAG ${FLANN_VERSION}
        PREFIX ${BUILD_DIR}
        BUILD_ALWAYS 0
        SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/${FLANN_TARGET}
        BINARY_DIR ${BUILD_DIR}/${FLANN_TARGET}_build
        INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
	CMAKE_ARGS
	    ${CMAKE_CORE_BUILD_FLAGS}
            -DBUILD_C_BINDINGS=OFF
            -DBUILD_EXAMPLES=OFF
            -DBUILD_TESTS=OFF
            -DBUILD_DOC=OFF
            -DBUILD_PYTHON_BINDINGS=OFF
            -DBUILD_MATLAB_BINDINGS=OFF
	    #${LZ4_CMAKE_FLAGS}
	    -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
            -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
	    <SOURCE_DIR>
        BUILD_COMMAND $(MAKE) -j${AV_BUILD_DEPENDENCIES_PARALLEL}
        DEPENDS ${LZ4_TARGET}
)

set(FLANN_CMAKE_FLAGS -Dflann_DIR:PATH=${CMAKE_INSTALL_PREFIX}/lib/cmake/flann/)
