if(WIN32)
   set(VORPALINE_PLATFORM Win-vs-dynamic-generic)
elseif(APPLE)
   set(VORPALINE_PLATFORM Darwin-clang-dynamic)
elseif(UNIX)
   set(VORPALINE_PLATFORM Linux64-gcc-dynamic)
endif()
set(GEOGRAM_TARGET geogram)
ExternalProject_Add(${GEOGRAM_TARGET}
       URL ${GEOGRAM_URI}
       URL_HASH ${GEOGRAM_HASH_TYPE}=${GEOGRAM_HASH}
       DOWNLOAD_DIR ${BUILD_DIR}/download/geogram
       PREFIX ${BUILD_DIR}
       BUILD_ALWAYS 0
       SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/geogram
       BINARY_DIR ${BUILD_DIR}/geogram_internal_build
       INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
       CMAKE_ARGS ${CMAKE_CORE_BUILD_FLAGS}
           ${ZLIB_CMAKE_FLAGS}
           -DVORPALINE_PLATFORM=${VORPALINE_PLATFORM}
           -DGEOGRAM_WITH_HLBFGS=OFF
           -DGEOGRAM_WITH_TETGEN=OFF
           -DGEOGRAM_WITH_GRAPHICS=OFF
           -DGEOGRAM_WITH_EXPLORAGRAM=OFF
           -DGEOGRAM_WITH_LUA=OFF
           -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
           <SOURCE_DIR>
       BUILD_COMMAND $(MAKE) -j${AV_BUILD_DEPENDENCIES_PARALLEL}
       DEPENDS ${ZLIB_TARGET}
)

set(GEOGRAM_CMAKE_FLAGS
    -DGEOGRAM_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DGEOGRAM_INCLUDE_DIR=${CMAKE_INSTALL_PREFIX}/include/geogram1
)

