
set(GDKPIXBUF2_MODULE_DIR "<INSTALL_DIR>/lib/gdk-pixbuf/loaders")

ExternalProject_Add(
    ${HEIF_TARGET}
    GIT_REPOSITORY ${HEIF_URI}
    GIT_TAG ${HEIF_VERSION}
    PREFIX ${BUILD_DIR}
    DOWNLOAD_DIR ${BUILD_DIR}/download/${HEIF_TARGET}
    SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/${HEIF_TARGET}
    BINARY_DIR ${BUILD_DIR}/${HEIF_TARGET}_build
    INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
    CMAKE_ARGS
        ${CMAKE_CORE_BUILD_FLAGS}
        -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
        -DCMAKE_INSTALL_LIBDIR=lib
	-DGDKPIXBUF2_MODULE_DIR=<INSTALL_DIR>/lib/gdk-pixbuf/loaders
        -DBUILD_SHARED_LIBS=ON
        -DWITH_EXAMPLES=OFF
    BUILD_COMMAND $(MAKE) -j${AV_BUILD_DEPENDENCIES_PARALLEL}
    DEPENDS ${ZLIB_TARGET} ${PNG_TARGET} ${JPEG_TARGET} ${X265_TARGET}
)

#set(HEIF_CMAKE_FLAGS -DHEIF_LIBRARY=${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/libpng${CMAKE_SHARED_LIBRARY_SUFFIX} -DHEIF_INCLUDE_DIR=${CMAKE_INSTALL_PREFIX}/include)
