# Add turbojpeg
ExternalProject_Add(${JPEG_TARGET}
       URL ${JPEG_URI}
       URL_HASH ${JPEG_HASH_TYPE}=${JPEG_HASH}
       DOWNLOAD_DIR ${BUILD_DIR}/download/${JPEG_TARGET}
       PREFIX ${BUILD_DIR}
       BUILD_ALWAYS 0
       SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/${JPEG_TARGET}
       BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR}/${JPEG_TARGET}_build
       INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
       CMAKE_ARGS 
	   -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
	   -DCMAKE_INSTALL_LIBDIR=${CMAKE_INSTALL_PREFIX}/lib
           -DENABLE_STATIC=ON
           -DWITH_JPEG8=ON
           -DWITH_JPEG7=ON
           -WITH_TURBOJPEG=ON
	   #${CMAKE_CORE_BUILD_FLAGS}
	   #${ZLIB_CMAKE_FLAGS}
	   #<SOURCE_DIR>
       BUILD_COMMAND $(MAKE) -j${AV_BUILD_DEPENDENCIES_PARALLEL}
       INSTALL_COMMAND $(MAKE) install
       DEPENDS ${ZLIB_TARGET}
)

set(JPEG_CMAKE_FLAGS
	-DJPEG_LIBRARY=${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/libjpeg${CMAKE_SHARED_LIBRARY_SUFFIX}
	-DJPEG_INCLUDE_DIR=${CMAKE_INSTALL_PREFIX}/include
)
