ExternalProject_Add(${LZ4_TARGET}
    URL ${LZ4_URI}
    URL_HASH ${LZ4_HASH_TYPE}=${LZ4_HASH}
    PREFIX ${BUILD_DIR}
    BUILD_ALWAYS 0
    SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/${LZ4_TARGET}
    BINARY_DIR ${BUILD_DIR}/${LZ4_TARGET}_build
    CMAKE_ARGS
        -S <SOURCE_DIR>/build/cmake
        -B .
        ${CMAKE_CORE_BUILD_FLAGS}
        -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
        -DCMAKE_INSTALL_LIBDIR=lib
	-DLZ4_BUILD_CLI=OFF
	-DLZ4_BUILD_LEGACY_LZ4C=OFF
    BUILD_COMMAND $(MAKE) -j${AV_BUILD_DEPENDENCIES_PARALLEL}
    INSTALL_COMMAND $(MAKE) install/strip
)

set(LZ4_CMAKE_FLAGS -Dlz4_DIR:PATH=${CMAKE_INSTALL_PREFIX}/lib/cmake/lz4/)
