ExternalProject_Add(${OPENIMAGEIO_TARGET}
    URL ${OPENIMAGEIO_URI}
    URL_HASH ${OPENIMAGEIO_HASH_TYPE}=${OPENIMAGEIO_HASH}
    DOWNLOAD_DIR ${BUILD_DIR}/download/${OPENIMAGEIO_TARGET}
    PREFIX ${BUILD_DIR}
    BUILD_ALWAYS 0
    SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/openimageio
    BINARY_DIR ${BUILD_DIR}/openimageio_build
    INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
    CMAKE_ARGS
        ${CMAKE_CORE_BUILD_FLAGS}
        -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
        -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
        -DBOOST_ROOT=${CMAKE_INSTALL_PREFIX}
        -DILMBASE_HOME=${CMAKE_INSTALL_PREFIX}
        -DOPENEXR_HOME=${CMAKE_INSTALL_PREFIX}
        ${ZLIB_CMAKE_FLAGS}
        -DSTOP_ON_WARNING=OFF
        -DUSE_FFMPEG=${AV_BUILD_FFMPEG}
        -DUSE_TURBOJPEG=${AV_BUILD_JPEG}
        ${JPEG_CMAKE_FLAGS}
        -DUSE_LIBRAW=${AV_BUILD_LIBRAW}
        ${LIBRAW_CMAKE_FLAGS}
        -DUSE_OPENEXR=${AV_BUILD_OPENEXR}
        ${OPENEXR_CMAKE_FLAGS}
        -DUSE_TIFF=${AV_BUILD_TIFF}
        ${TIFF_CMAKE_FLAGS}
        -DUSE_PNG=${AV_BUILD_PNG}
        ${PNG_CMAKE_FLAGS}
        -DUSE_PYTHON=OFF
	-DUSE_OPENCV=OFF
	-DUSE_OPENGL=OFF
        -DOIIO_BUILD_TESTS=OFF
        -DOIIO_BUILD_TOOLS=OFF
	<SOURCE_DIR>
    BUILD_COMMAND $(MAKE) -j${AV_BUILD_DEPENDENCIES_PARALLEL}
    DEPENDS ${BOOST_TARGET} ${OPENEXR_TARGET} ${TIFF_TARGET} ${PNG_TARGET} ${JPEG_TARGET} ${LIBRAW_TARGET} ${ZLIB_TARGET} ${FFMPEG_TARGET} ${HEIF_TARGET}
)

# TODO: openjpeg
# -DOPENJPEG_INCLUDE_DIR=$OPENJPEG_INCLUDE_DIR/openjpeg-2.0 -DOPENJPEG_OPENJP2_LIBRARIES=$OPENJPEG_OPENJP2_LIBRARIES
set(OPENIMAGEIO_CMAKE_FLAGS -DOpenImageIO_DIR=${CMAKE_INSTALL_PREFIX})
