ExternalProject_Add(${OPENEXR_TARGET}
      # vfxplatform CY2022: 3.1.x
      URL ${OPENEXR_URI}
      URL_HASH ${OPENEXR_HASH_TYPE}=${OPENEXR_HASH}
      DOWNLOAD_DIR ${BUILD_DIR}/download/openexr
      PREFIX ${BUILD_DIR}
      BUILD_ALWAYS 0
      SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/openexr
      BINARY_DIR ${BUILD_DIR}/openexr_build
      INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
      CMAKE_ARGS
             ${CMAKE_CORE_BUILD_FLAGS} 
             -DOPENEXR_BUILD_PYTHON_LIBS:BOOL=OFF 
             -DBUILD_TESTING:BOOL=OFF 
             -DOPENEXR_INSTALL_EXAMPLES:BOOL=OFF
             -DOPENEXR_BUILD_TOOLS:BOOL=OFF
             ${ZLIB_CMAKE_FLAGS} 
             -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR> 
             <SOURCE_DIR>
      BUILD_COMMAND VERBOSE=1 $(MAKE) -j${AV_BUILD_DEPENDENCIES_PARALLEL}
      DEPENDS ${ZLIB_TARGET}
)

set(ILMBASE_CMAKE_FLAGS -DILMBASE_ROOT=${CMAKE_INSTALL_PREFIX} -DILMBASE_INCLUDE_PATH=${CMAKE_INSTALL_PREFIX}/include/OpenEXR)
set(OPENEXR_CMAKE_FLAGS ${ILMBASE_CMAKE_FLAGS} -DOPENEXR_ROOT=${CMAKE_INSTALL_PREFIX} -DOPENEXR_INCLUDE_PATH=${CMAKE_INSTALL_PREFIX}/include)
