if(${CMAKE_SYSTEM_PROCESSOR} MATCHES "arm") 
    set(AV_PNG_ARM_NEON on)
else()
    set(AV_PNG_ARM_NEON off)
endif()

ExternalProject_Add(${PNG_TARGET}
       URL ${PNG_URI}
       URL_HASH ${PNG_HASH_TYPE}=${PNG_HASH}
       DOWNLOAD_DIR ${BUILD_DIR}/download/libpng
       PREFIX ${BUILD_DIR}
       BUILD_ALWAYS 0
       SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/png
       BINARY_DIR ${BUILD_DIR}/png_build
       INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
       # CONFIGURE_COMMAND <SOURCE_DIR>/configure --prefix=<INSTALL_DIR>
       CMAKE_ARGS
           ${CMAKE_CORE_BUILD_FLAGS}
           ${ZLIB_CMAKE_FLAGS}
           -DPNG_ARM_NEON=${AV_PNG_ARM_NEON}
           -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
	   -DPNG_BUILD_ZLIB=OFF
	   -DPNG_EXECUTABLES=OFF
           <SOURCE_DIR>
       BUILD_COMMAND $(MAKE) -j${AV_BUILD_DEPENDENCIES_PARALLEL}
       INSTALL_COMMAND $(MAKE) install/strip
       DEPENDS ${ZLIB_TARGET}
)

set(PNG_CMAKE_FLAGS -DPNG_LIBRARY=${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/libpng${CMAKE_SHARED_LIBRARY_SUFFIX} -DPNG_INCLUDE_DIR=${CMAKE_INSTALL_PREFIX}/include)
