ExternalProject_Add(${POPSIFT_TARGET}
      GIT_REPOSITORY ${POPSIFT_URI} 
      GIT_TAG ${POPSIFT_VERSION}
      PREFIX ${BUILD_DIR}
      BUILD_ALWAYS 0
      SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/popsift
      BINARY_DIR ${BUILD_DIR}/popsift_build
      INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
      CMAKE_ARGS
          ${CMAKE_CORE_BUILD_FLAGS}
          ${BOOST_CMAKE_FLAGS}
          ${CUDA_CMAKE_FLAGS}
          -DPopSift_BUILD_EXAMPLES:BOOL=OFF
          -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
          <SOURCE_DIR>
      BUILD_COMMAND $(MAKE) -j${AV_BUILD_DEPENDENCIES_PARALLEL}
      DEPENDS ${BOOST_TARGET} ${CUDA_TARGET}
)

set(POPSIFT_CMAKE_FLAGS -DPopSift_DIR:PATH=${CMAKE_INSTALL_PREFIX}/lib/cmake/PopSift)
