ExternalProject_add(
    ${X265_TARGET}
    GIT_REPOSITORY ${X265_URI}
    GIT_TAG ${X265_VERSION}
    PREFIX ${BUILD_DIR}
    DOWNLOAD_DIR ${BUILD_DIR}/download/${X265_TARGET}
    SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/${X265_TARGET}
    BINARY_DIR ${BUILD_DIR}/${X265_TARGET}_build
    INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
    CMAKE_ARGS
        -B .
        -S <SOURCE_DIR>/source
        -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
        -DENABLE_SHARED=ON
        -DENABLE_PIC=ON
    BUILD_COMMAND $(MAKE) -j${AV_BUILD_DEPENDENCIES_PARALLEL}
)
