if(AV_BUILD_ZLIB)
ExternalProject_Add(${ZLIB_TARGET}
       URL ${ZLIB_URI}
       URL_HASH ${ZLIB_HASH_TYPE}=${ZLIB_HASH}
       DOWNLOAD_DIR ${BUILD_DIR}/download/${ZLIB_TARGET}
       PREFIX ${BUILD_DIR}
       BUILD_ALWAYS 0
       SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/${ZLIB_TARGET}
       BINARY_DIR ${BUILD_DIR}/${ZLIB_TARGET}_build
       INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
       CMAKE_ARGS
         ${CMAKE_CORE_BUILD_FLAGS}
	 -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
         <SOURCE_DIR>
       BUILD_COMMAND $(MAKE) -j${AV_BUILD_DEPENDENCIES_PARALLEL}
       INSTALL_COMMAND $(MAKE) install/strip
)
set(ZLIB_CMAKE_FLAGS -DZLIB_ROOT=${CMAKE_INSTALL_PREFIX})
endif()
